version: '3'
services:
  client:
    build:
      context: ./client
    volumes: 
      - "$PWD/client:/app/client"
      - node_modules:/app/client/node_modules
    ports:
      - 3434:3434
    depends_on:
      - server
  server:
    build:
      context: ./server
    volumes: 
      - "$PWD/server:/app/server"
      - server_node_modules:/app/server/node_modules
    ports:
      - 3535:3535

volumes:
  node_modules:
  server_node_modules:
